### ISSUE TITLE
Unable to edit size of burger button on mobile

### ISSUE THREAD

**Issue by RTK99** [mbj36/vue-burger-menu#3]
Hi, 
So I'm primarily using this burger menu on a mobile device. I saw the css for the element you posted, and I decided to edit it for myself. Here is how I did it:
```css
.bm-burger-button {
      position: relative;
      width: 30px;
      height: 24px;
      left: 36px;
      top: 36px;
      cursor: pointer;
    }
```
I edited the width and the height, since the button was extending out of my navbar. However, the size did not change. On desktop though, the changes are noticeable. 
something is preventing the style from being changed on mobile.
Thanks,
RTK99
